version: '3.8'

services:
  frontend:
    build:
      context: ./simple_react_project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./simple_react_project:/app
    command: ["npm", "run", "start"]
